### PR TITLE
Allow exit after frame for text and oneLine mode

### PR DESCRIPTION
**Pull request by timoschwarzer**
This allows users exiting after the current frame has been rendered while using the text or oneLine mode.

How it works:
If it's rendering, hit Ctrl-C to exit after the current frame (a message will appear in the console) (this is calling `client.askForStop()`.
Hitting Ctrl-C again will stop the client instantly (this is calling `client.stop()`).

If there should be problems with the client not exiting properly (because of uncatched exceptions etc.) I've built in an "emergency exit": Hitting Ctrl-C five times will force close the application instantly (But this should not be used because it won't remove temp files etc.).

### CODE REVIEW

**Comment by laurent-clouet** [comment]
I don't compile on my ubuntu with openjdk 7u79-2.5.6-0ubuntu1.14.04.1
    [javac] Compiling 39 source files to /tmp/SheepitClient.svn/build
    [javac] /tmp/SheepitClient.svn/src/com/sheepit/client/standalone/GuiText.java:48: error: illegal start of expression
    [javac] 			Signal.handle(new Signal("INT"), signal -> {
    [javac] 			                                         ^
    [javac] /home/laurent/temp/workspace/SheepitClient.svn/src/com/sheepit/client/standalone/GuiText.java:48: error: illegal start of expression
    [javac] 			Signal.handle(new Signal("INT"), signal -> {
    [javac] 			                                           ^
    [javac] /home/laurent/temp/workspace/SheepitClient.svn/src/com/sheepit/client/standalone/GuiText.java:48: error: ';' expected
    [javac] 			Signal.handle(new Signal("INT"), signal -> {
    [javac] 			                                            ^

I'm guessing you used an java8 feature.

**Comment by timoschwarzer** [comment]
Jep, sorry. Removed java8 syntax... Should work now.

**Comment by AGSPhoenix** [comment]
It seems to build now with OpenJDK 1.7.0_91, albeit with plenty of warnings about the API being proprietary and not guaranteed to exist in future releases. If they do end up removing it, there's some chance an official replacement would be provided.

I wasn't able to do more than a few tests on my VM with Java 7, but assuming it works as intended, I'm fully behind this PR. I had been planning on trying to implement this myself sometime in the coming weeks, as I'd really like this feature, so I'd be happy to see this accepted.

**Comment by laurent-clouet** [comment]
It's on my todo list, simply need some time to do some tests.

**Comment by timoschwarzer** [comment]
@AGSPhoenix maybe we should come up with another solution than intercepting SIGINT then...

**Comment by AGSPhoenix** [comment]
@timoschwarzer I'm not sure if there any any obviously better alternatives. Signals are built into every OS the client supports, and are familiar to every command line user. Although the API is unofficial, much of the discussion I've found online seems to conclude that it is unlikely to be removed, and if it is, some alternative would be provided. [JEP 260](http://openjdk.java.net/jeps/260) states that `Signal` and `SignalHandler` will remain in Java 9 at the very least.

One alternative would be to accept command line input, like with the readline library, but that would be a large amount of work to add just one feature. There is some community interest in this, like MaxPlay's suggestion on the roadmap with 130 votes:

>Add an in-console-command line, which can be used during the render (e.g. "time" to look at the time that passed or that has to pass until the render is finished).

However, that's not a large amount of interest, and I'm not sure it's worth it when everything proposed can be found by looking at the host details on the site itself.

Another alternative I looked into would be to use a shutdown hook, but [the official Java 7 docs](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)) on Oracle's site state:

> Shutdown hooks should [...] finish their work quickly. When a program invokes `exit` the expectation is that the virtual machine will promptly shut down and exit. When the virtual machine is terminated due to user logoff or system shutdown the underlying operating system may only allow a fixed amount of time in which to shut down and exit. It is therefore inadvisable to attempt any user interaction or to perform a long-running computation in a shutdown hook.

This is clearly not a good solution either.

Assuming the code works on all platforms, this seems to me like the best way to proceed for now.

**Comment by timoschwarzer** [comment]
@AGSPhoenix I first tried shutdown hooks, but I found no way to cancel the shutdown and wait untit something happens. So I had to use Signals.

**Comment by laurent-clouet** [comment]
Merged with 5997faec86cb27aa52b0dbfa2729ccc050d7181
Thanks for the pull request !
